version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api:
    build: .
    container_name: api
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    ports:
      - 8080:8080
    depends_on:
      - mongodb

volumes:
  mongodb_data_container: